# Generated by Django 3.2.7 on 2022-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'главный', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterField(
            model_name='home',
            name='telegram',
            field=models.CharField(blank=True, help_text='https://t.me/edzn21', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='youtube',
            field=models.CharField(blank=True, help_text='https://www.youtube.com/c/selfedu_rus', max_length=150),
        ),
    ]
