# Generated by Django 3.2 on 2022-03-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'главный', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='telegram',
            field=models.CharField(blank=True, help_text='https://t.me/edzn21', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='youtube',
            field=models.CharField(blank=True, help_text='https://www.youtube.com/c/selfedu_rus', max_length=150),
        ),
    ]
