# Generated by Django 3.2 on 2022-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('link_partner', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='parners/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'партнёра',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tarif', models.CharField(max_length=100, verbose_name='Название')),
                ('price_tarif', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'партнёра',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='RichTextUploadingField',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service/', verbose_name='Фото'),
        ),
    ]
