# Generated by Django 3.2 on 2022-03-03 10:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220303_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Фото'),
        ),
    ]
