# Generated by Django 3.2 on 2022-03-03 10:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_price_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'цена', 'verbose_name_plural': 'Цена'},
        ),
        migrations.AlterField(
            model_name='price',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_tarif',
            field=models.CharField(help_text='$45 / Месяц или $Бесплатно / Месяц', max_length=250, null=True, verbose_name='цена'),
        ),
    ]
