# Generated by Django 3.2.7 on 2022-03-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_home_logo'),
        ('home', '0006_auto_20220303_1653'),
    ]

    operations = [
    ]
