# Generated by Django 3.2.7 on 2022-03-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_0005_alter_home_logo_0006_auto_20220303_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='RichTextUploadingField',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
