# Generated by Django 3.2.7 on 2022-03-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220305_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='link_partner',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на партнера'),
        ),
    ]
